---
theme: jekyll-theme-cayman

title: [Rohith Srinivaas M]
description: [One with a curious mind !]

include: ['_posts', '_pages']

baseurl: ""

social_links:
  github: "https://github.com/rohithsrinivaas/"
  linkedin: "https://linkedin.com/in/"
  # quora: "https://www.quora.com/profile/Abhishek-Naik-20/"
  # goodreads: "https://www.goodreads.com/user/show/41821528-abhishek-naik"

plugins:
  #- jekyll-twitter-plugin

github: [metadata]

markdown: kramdown

#google_analytics: UA-144379474-1

repository: rohithsrinivaas/rohithsrinivaas.github.io

---
